version: '3.8'

services:
  phishing-simulation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Expose le port 80 du conteneur sur le port 8080 de la machine hôte
    volumes:
      - log-data:/var/log/ # Monte un volume pour persister les logs même si le conteneur est recréé
    restart: unless-stopped

volumes:
  log-data: # Volume pour stocker le fichier log.csv
